name: macos-arm-vnc 

on: workflow_dispatch

jobs:
  run:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: setup vnc and password
        run: |
          sudo dscl . -passwd /Users/runner password123
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -restart -agent -privs -all
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvncpw -vncpw 12345678

      - name: start session
        run: |
          # Download bore untuk macOS (Apple Silicon / aarch64)
          curl -sL https://github.com/ekzhang/bore/releases/download/v0.6.0/bore-v0.6.0-aarch64-apple-darwin.tar.gz | tar -xz
          sudo mv bore /usr/local/bin/
          
          # Jalankan bore di port 5900 (Port default VNC/Screen Sharing di Mac)
          bore local 5900 --to bore.pub > bore.log 2>&1 &
          
          sleep 5
          cat bore.log
          
      - name: keep alive 
        run: |
         end=$((SECONDS+21600))
         while [ $SECONDS -lt $end ]; do
            echo "Time remaining: $(( (end - SECONDS) / 60 )) minutes"
            sleep 60
         done
